apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab8
  name: lab8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab8
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lab8
  name: lab8
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32001
  selector:
    app: lab8
status:
  loadBalancer: {}
