apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab14pod
  name: lab14pod
spec:
  containers:
  - image: nginx
    name: lab14pod
    readinessProbe:
      exec:
	command:
	- cat
	- /etc/hosts
      initialDelaySeconds: 5
      periodSeconds: 5

