apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myuserpod
  name: myuserpod
spec:
  serviceAccountName: myuser
  containers:
  - image: httpd
    name: myuserpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
