apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: secret-ops
spec: {}
status: {}


--- 
apiVersion: v1
data:
  API_KEY: TG1MSGJZaHNnV1p3TmlmaXFhUm9ySDhUQQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ext-service-secret
  namespace: secret-ops

--- 

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: consumer
    resources: {}
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: ext-service-secret
          key: API_KEY
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
