apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: older-version
    type: cy
  name: nginxservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: cy
status:
  loadBalancer: {}
