apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: older-version
    type: cy
  name: older-version
spec:
  replicas: 3
  selector:
    matchLabels:
      app: older-version
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: older-version
        type: cy
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html/
      volumes:
        - name: index-html
          configMap:
            name: older-index
