apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: limitrange
spec:
  limits:
  - max: # max and min define the limit range
      memory: 500Mi
    min:
      memory: 100Mi
    type: Container

