apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: n2
  name: n2
spec:
  containers:
  - image: nginx
    name: n2
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret2

  restartPolicy: Always
status: {}
