apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: n3
  name: n3
spec:
  containers:
  - image: nginx
    name: n3
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: mysecret2
          key: username
 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
