apiVersion: v1
kind: Pod
metadata:
  name: nginx-options
spec:
  containers:
    - name: nginx-options
      image: nginx
      env:
        # Define the environment variable
        - name: var5
          valueFrom:
            configMapKeyRef:
              name: options
              key: var5
  restartPolicy: Never
