apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: parallel5
spec:
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - sleep
        - "20"
        image: busybox
        name: parallel5
        resources: {}
      restartPolicy: Never
status: {}
