apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rednginx
    version: v1
    type: canary
  name: rednginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rednginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rednginx
        type: canary
        version: v1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
