apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: repeat5
spec:
  completions: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - sleep
        - "20"
        image: busybox
        name: repeat5
        resources: {}
      restartPolicy: Never
status: {}
