apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rqnginx
  name: rqnginx
  namespace: limitrange
spec:
  containers:
  - image: nginx
    name: rqnginx
    resources: 
      requests:
        memory: 250Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
