
### This has been created by Sander van Vugt from his CKAD course. Repo take from: github.com/sandervanvugt/ckad
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "64Gi"
        cpu: "250m"
      limits:
        memory: "128Gi"
        cpu: "500m"
  - name: wp
    image: wordpress
    resources:
      requests:
        memory: "64Gi"
        cpu: "250m"
      limits:
        memory: "128Gi"
        cpu: "500m"
