apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lab11nginx
  name: lab11nginx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lab11nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab11nginx
    spec:
      containers:
      - env:
        - name: MYPASSWORD
          valueFrom:
            secretKeyRef:
              key: MYPASSWORD
              name: my-secret
        volumeMounts: 
        - name: lab11-config
          mountPath: /usr/share/nginx/html

        
        image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      volumes:
      - name: lab11-config
        configMap:
          name: my-config
      restartPolicy: Always
