apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: jobviacode
spec:
  ttlSecondsAfterFinished: 5
  completions: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - date
        image: busybox
        name: jobviacode
        resources: {}
      restartPolicy: Never
status: {}
