apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: secret
spec: {}
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lab5busybox
  name: lab5busybox
  namespace: secret
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: lab5busybox
    resources: 
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
    
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
