apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-example
spec:
  containers:
  - name: multicontainer-example-1
    image: busybox 
    command:
      - sleep
      - "3600"

  - name: multicontainer-example-2
    image: nginx




