apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab4-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab4-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: lab4-pv-pod
spec:
  volumes:
    - name: cmvol
      persistentVolumeClaim:
        claimName: lab4-pv-claim
  containers:
    - name: lab4-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: cmvol


