apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod
  name: alpine-pod
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine:3.9
    name: alpine-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
