apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lala-nginx
  name: lala-nginx
spec:
  containers:
  - image: nginx
    name: lala-nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/lala

    resources: {}
  dnsPolicy: ClusterFirst
  volumes:
  - name: config-volume
    configMap:
      name: cmvolume
  restartPolicy: Always
status: {}
