apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-anotherone
  name: nginx-anotherone
spec:
  containers:
  - image: nginx
    name: nginx-anotherone
    env:
    - name: var6
      valueFrom:
        configMapKeyRef:
          name: anotherone
          key: var6

    - name: var7
      valueFrom:
        configMapKeyRef:
          name: anotherone
          key: var7
    
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
