apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ren1
  name: ren1
spec:
  containers:
  - image: nginx:latest
    name: ren1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
