apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: spod
  name: spod
spec:
  SecurityContext:
    runAsUser: 101
    capabilities:
      add: ["NET_ADMIN", "SYS_TIME"]
  containers:
  - image: nginx
    name: spod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
